config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'parser/index'
  get 'parser/scraperbash'
  get 'parser/scraperarduino'
  get 'parser/scraperyaplakal'
  get 'parser/thenextweb'
  root 'parser#scraper'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/parser_controller.rb
class ParserController < ApplicationController
  require 'nokogiri'
  require 'open-uri'


  def scraperbash
    @bash=[]
    # Fetch and parse HTML document
    doc = Nokogiri::HTML(open('https://pikabu.ru/'))


    doc.css('.story__datetime').each do |link|
        @bash.push(link)
    end

  end


  def scraperarduino
    require 'nokogiri'
    require 'open-uri'
    @arduino=[]
    # Fetch and parse HTML document
    doc = Nokogiri::HTML(open('http://arduino.ru/projects'))

    puts "### Search for nodes by css"
    doc.css('.views-row').each do |link|
      # puts '------------------------------'
      # puts link.text

      @arduino.push(link)
    end

  end

  def scraperyaplakal
    require 'nokogiri'
    require 'open-uri'
    @yap=[]
    @yap_content=[]
    # Fetch and parse HTML document
    doc = Nokogiri::HTML(open('http://www.yaplakal.com/'))
    limit=0
    doc.css('.newshead').each do |link|
      # puts '------------------------------'
      # puts link.text
      limit = limit+1
      if(limit < @limit)
        @link_array.push(link)
      else
        break
      end
    end

  end


  def thenextweb
    require 'nokogiri'
    require 'open-uri'
    @web=[]

    # Fetch and parse HTML document
    for i in 1..10
      doc = Nokogiri::HTML(open('https://thenextweb.com/latest/page/'+i.to_s))

      doc.css('.u-col-xs-6').each do |link|
        # puts '------------------------------'
        # puts link.text

        @web.push(link)
      end
     end
  end

  def scraper
    @link_array_header = []
    @link_array_body = []
    @link_array_info = []
    @limit = 10

    name_site = 'http://www.yaplakal.com/'
    doc = Nokogiri::HTML(open(name_site))

    if (name_site = 'http://www.yaplakal.com/')
        limit = 0
        doc.css('.newshead').each do |link|
          limit = limit+1
          if(limit <= @limit)
            @link_array_header.push(link)
          else
            break
          end
        end

        limit = 0
        doc.css('.postcolor').each do |link|
          limit = limit+1
          if(limit <= @limit)
            @link_array_body.push(link)
          else
            break
          end
        end

        limit = 0
        doc.css('.icon-date').each do |link|
          limit = limit+1
          if(limit <= @limit)
            @link_array_info.push(link)
          else
            break
          end
        end

    end


    name_site = 'https://pikabu.ru/'
    doc = Nokogiri::HTML(open(name_site))

    if (name_site = 'https://pikabu.ru/')
      limit = 0
      doc.css('.story__header').each do |link|
        limit = limit+1
        if(limit <= @limit)
          @link_array_header.push(link)
        else
          break
        end
      end

      limit = 0
      doc.css('.story__content').each do |link|
        limit = limit+1
        if(limit <= @limit)
          @link_array_body.push(link)
        else
          break
        end
      end

      limit = 0
      doc.css('.story__datetime').each do |link|
        limit = limit+1
        if(limit <= @limit)
          @link_array_info.push(link)
        else
          break
        end
      end

    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parser_helper.rb
module ParserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParserBash</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/parser/index.html.erb
<div class="row">
  <div class="col-md-12">
    <header>
      <h1 class="text-center">Парсер сайтов:</h1>
    </header>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <ul class="list-group">
      <li class="list-group-item"><%= link_to 'Парсим bash.im', parser_scraperbash_path %></li>
      <li class="list-group-item"><%= link_to 'Парсим arduino.ru/projects', parser_scraperarduino_path %></li>
      <li class="list-group-item"><%= link_to 'Парсим yaplakal.com', parser_scraperyaplakal_path %></li>
      <li class="list-group-item"><%= link_to 'Парсим thenextweb', parser_thenextweb_path%></li>

    </ul>
  </div>
</div>



<br>

<br>

app/views/parser/scraper.html.erb
    <div class="row">
      <div class="col-md-12">
        <header>
          <h1 class="text-center">Отдохни:</h1>
        </header>
      </div>
    </div>

<div class="row">
   <div class="col-md-12">
 <table id="link_tables" class="table">
      <thead>
      <tr>
        <td>
      Свежачек:
        <td>
      <tr>
      </thead>
      <tbody>

    <% @link_array_header.each_with_index {|link,index |  %>
          <tr>
          <td>

          <div>
            <h4><%= link.text %></h4>

            <a href="#myModal<%=index%>" class="btn btn-primary" data-toggle="modal">Подробнее</a>
            <%= link_to("Открыть",link.css('a')[0]['href'] , method: :get, target: "_blank",class:"btn btn-primary" )%>

            <%if(@link_array_info.length > 0) %>
                <%= @link_array_info[index].text %>
            <% end %>

            <%= link.css('a')[0]['href'] %>

            <div id="myModal<%=index%>" class="modal fade">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title"><%= link.text %></h4>
                  </div>
                  <div class="modal-body">
                    <%if(@link_array_body.length > 0) %>
                        <div>
                          <div>
                            <% if (@link_array_body[index].css('img')).present? %>
                              <%=image_tag(@link_array_body[index].css('img')[0]["src"],width: 560, height: 315) %>
                            <% end %>

                            <% if (@link_array_body[index].css('iframe')).present? %>
                              <%= content_tag(:iframe, '', src: @link_array_body[index].css('iframe')[0]["src"],
                                              width: 560, height: 315, frameborder: 0) %>
                            <% end %>
                          </div>
                          <%= @link_array_body[index].text %>
                        </div>
                    <%end %>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
          </td>
          </tr>
    <%} %>
      </tbody>
    </table>
   </div>
</div>

app/views/parser/scraperarduino.html.erb
<div class="row">
  <div class="col-md-12">
    <header>
      <h1 class="text-center">Проэкты ардуино:</h1>
    </header>
  </div>
</div>

<% @arduino.each do |arduino| %>
   <div class="row">
      <div class="col-md-12">
        <h4><%= arduino.css('.views-field-title').text %></h4>
        <div>
          <% if (arduino.css('.views-field-teaser img')).present? %>
              <%=image_tag("http://arduino.ru"+arduino.css('.views-field-teaser img')[0]["src"]) %>
          <% end %>

          <% if (arduino.css('.views-field-teaser iframe')).present? %>
              <%= content_tag(:iframe, '', src: arduino.css('.views-field-teaser iframe')[0]["src"],
                              width: 560, height: 315, frameborder: 0) %>
          <% end %>
        </div>
        <div>
          <%= arduino.css('.views-field-teaser').text %>
        </div>
        <div>
          <%= link_to("Подробнее","http://arduino.ru"+arduino.css('.views-field-path a')[0]['href'] , method: :get, target: "_blank")%>
        </div>
      </div>
    </div>

 <% end %>

app/views/parser/scraperbash.html.erb
<div class="row">
  <div class="col-md-12">
    <header>
      <h1 class="text-center">Цитатник рунета:</h1>
    </header>
  </div>
</div>

<% @bash.each do |bash| %>

    <div class="row">
      <div class="col-md-12">
            <%= bash.text %>
        <hr>

      </div>
    </div>

<% end %>

app/views/parser/scraperyaplakal.html.erb
<div class="row">
  <div class="col-md-12">
    <header>
      <h1 class="text-center">Яплакалъ:</h1>
    </header>
  </div>
</div>

<% for i in 0..@yap.length-1 %>

    <div class="row">
      <div class="col-md-12">
        <h4><%= @yap[i].text %></h4>
        <div>

          <div>
            <% if (@yap_content[i].css('img')).present? %>
                <%=image_tag(@yap_content[i].css('img')[0]["src"]) %>
            <% end %>

            <% if (@yap_content[i].css('iframe')).present? %>
                <%= content_tag(:iframe, '', src: @yap_content[i].css('iframe')[0]["src"],
                                width: 560, height: 315, frameborder: 0) %>
            <% end %>
          </div>

          <%= @yap_content[i].text %>

          <div>
            <%= link_to("Подробнее",@yap[i].css('a')[0]['href'] , method: :get, target: "_blank")%>
          </div>

        </div>
      </div>
    </div>

<% end %>

app/views/parser/thenextweb.html.erb
<% @web.each do |web| %>

    <% if web.css('.story-title').present?%>
      <div>
        <div>
          <% if web.css('.story-image').present?%>
              <%=image_tag(web.css('.story-image')[0]["data-src"]) %>
          <% end %>

        </div>

        <h4><%= web.css('.story-title').text %></h4>

        <div>
          <%= web.css('.story-chunk').text %>
        </div>

        <div>
          <%= link_to("Подробнее",web.css('.story-title a')[0]['href'] , method: :get, target: "_blank")%>
        </div>
        <hr>
      </div>
    <% end %>
<% end %>